### ISSUE TITLE
Scope of this project

### ISSUE THREAD

**Issue by YujingYang666777** [mingkaid/rl-prompt#24]
Hello,

I understand that this paper aims to create discrete prompts for LM and this is one motivation to optimize discrete prompts for black box models. So in this case, this method is applicable for GPT-3 as well, with some modification on the model part. Is that correct?

I have another question about the scope of the project. There are two experiments, 1. few-shot text classification and 2. Unsupervised Text Style Transfer. However, I am wondering if I can apply the project to the task of question answering. If so, the reword function should encourage prompts to answer the question correctly or closely. Is that applicable?

Thanks!

**Comment by MM-IR** [comment]
Since it is a clarification, I will close this issue. Thanks!
