### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 18712234451** [mingkaid/rl-prompt#31]
Dear author, hello, I encountered a problem that I could not download the pre-trained model in the process of trying to run the code. I tried some methods but still could not solve it. Can you help me solve this doubt? Thank you so much

OSError: Can't load config for './examples/few-shot-classification/rlprompt/distgpt2/'. Make sure that:

- './examples/few-shot-classification/rlprompt/distgpt2/' is a correct model identifier listed on 'https://huggingface.co/models'

- or './examples/few-shot-classification/rlprompt/distgpt2/' is the correct path to a directory containing a config.json

**Comment by MM-IR** [comment]
Hi, I think you just used the incorrect model names/identifiers...

If you want to use DistilGPT2, please use the name "distilgpt2", instead of "distgpt2".

**Comment by MM-IR** [comment]
And please check your model_name string in your model logging line.

Since it is a clarification, I am closing it now.
