### ISSUE TITLE
Lack of evaluation in `modular-interface` branch

### ISSUE THREAD

**Issue by Dinxin** [mingkaid/rl-prompt#6]
It seems that there is not fully complete code for evaluation in the `modular-interface` branch.

**Comment by MM-IR** [comment]
Thanks for asking. I will upload it for few-shot classification today, then you can evaluate your prompt with our script. I’m closing this now because it’s a clarification question.

**Comment by Dinxin** [comment]
Can you also upload it for (few-shot) text style transfer?

**Comment by mingkaid** [comment]
The preliminary code for text style transfer evaluation is in the folder `examples/text-style-transfer/evaluation/modules`. We are working on a cleaner version that will be released later today or tomorrow. Please let us know if you have any specific questions

**Comment by mingkaid** [comment]
We've uploaded the clean code for text style transfer evaluation. You can find the detailed instructions [here](https://github.com/mingkaid/rl-prompt/tree/modular-interface/examples/text-style-transfer#evaluation)

Let us know if you have any questions
