### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Ericmututu** [mingkaid/rl-prompt#8]
When implementing the `run_fsc.py` in `examples\few-shot-classification\` following the direction of usages directly, I meet the error `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)`.  It seems that the model is on the GPU while the data on CPU. How do I fix it? 

Thanks in advance!

**Comment by MM-IR** [comment]
Hi, thanks for your question. I clarify that we have updated our codebase, did you try with our up-to-date codebase in main branch? I have run it in my machine, and everything works well. Also, it seems that your mentioned issues are resolved by us before.

**Comment by MM-IR** [comment]
Since it is a clarification thing, and if it is no other questions, I will close this issue now.
